services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=Aurora
      - serverIP=ghost
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - ./data/configs:/app/configs
      - ./data/logs:/app/logs
      # - /media:/media
      - /var/mnt/nas-media/tv/:/media/tv/:rw
      # - /transcode_cache:/temp
      - "/var/mnt/tank/tdarr_cache:/temp:rw"
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    depends_on:
      - tailscale
    network_mode: service:tailscale

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tdarr-node-tailnet
    hostname: tdarr-node
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /home/nic/docker-volume-data/tdarr/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    privileged: true
    entrypoint: ["tailscaled"]